### ISSUE TITLE
[ballerina/en] Link to page not working

### ISSUE THREAD

**Issue by Kaamkiya** [adambard/learnxinyminutes-site#112]
**Description**
The link from the [homepage](https://learnxinyminutes.com/) to the page about [ballerina](https://github.com/adambard/learnxinyminutes-docs/blob/master/ballerina.html.markdown) doesn't work.

**Reproduce**
1. Go to the [website](https://learnxinyminutes.com/)
2. Scroll down until you see "Ballerina"
3. Click the link
4. See 404 page

**Device**
OS: ChromeOS
Browser: Chrome

**Expected**
I expected the page about Ballerina to show up. It's in the [learnxinyminutes-docs](https://github.com/adambard/learnxinyminutes-docs) repo, but the link seems to fail.

**Comment by vendethiel** [comment]
Our pygments is reaaaaally outdated.

**Comment by vendethiel** [comment]
For now I pushed adambard/learnxinyminutes-docs#2dba5b129445a7455db9986b482327ebdbcc2c1c

**Comment by Kaamkiya** [comment]
Thank you! It's working now :)
