### ISSUE TITLE
[cue/en] Link to cue docs not working

### ISSUE THREAD

**Issue by Kaamkiya** [adambard/learnxinyminutes-site#113]
**Description**
The link from the [homepage](https://learnxinyminutes.com/) to the page about [cue](https://github.com/adambard/learnxinyminutes-docs/blob/master/cue.html.markdown) doesn't work.

**Reproduce**
1. Go to the [website](https://learnxinyminutes.com/)
2. Scroll down until you see "cue"
3. Click the link
4. See 404 page

**Device**
OS: ChromeOS
Browser: Chrome

**Expected**
I expected the page about Cue to show up. It's in the [learnxinyminutes-docs](https://github.com/adambard/learnxinyminutes-docs/blob/master/cue.html.markdown) repo, but the link seems to fail.

**More info**

I created a similar issue (#112) a couple of days ago. I wonder if something's wrong in deployment? It could be a kind of whack-a-mole situation, where push one temp fix causes another bug.
Sorry, I don't code in Ruby so I can't help :(

**Comment by vendethiel** [comment]
I tried to fix it in https://github.com/adambard/learnxinyminutes-docs/commit/8a264b945ac3d664ef8dc61e755ed9b6c3797513

**Comment by Kaamkiya** [comment]
For some reason, it still isn't working for me.

**Comment by Kaamkiya** [comment]
Sorry to bug you, but it's the same situation for tailspin. I didn't make another issue because it's the same problem, different link.

**Comment by vendethiel** [comment]
Right. I need to find a language that resembles tailspin enough that the highlighting isn't completely broken...

**Comment by vendethiel** [comment]
I switched it to C, let's see how that ends up looking on the website.

**Comment by Kaamkiya** [comment]
Now the link works, thanks!

**Comment by vendethiel** [comment]
Alright, thanks for the report.
