### ISSUE TITLE
Enhancement. Use github syntax highlight.

### ISSUE THREAD

**Issue by derek-austin** [adambard/learnxinyminutes-site#40]
Enhancement. Use github library "[linguist](https://github.com/github/linguist)" for syntax highlight.
Github renders ok [powershell/en page](https://github.com/adambard/learnxinyminutes-docs/blob/master/powershell.html.markdown), but https://learnxinyminutes.com/docs/powershell/ don't. Example where github does ok:
~~~ powershell
echo @"
This is a Here-String
$aString
"@
# Note that ' (single quote) won't expand the variables!
# Here-Strings also work with single quote
~~~

**Comment by adambard** [comment]
This seems ok now.
