### ISSUE TITLE
Google Chrome (Mac v62.0.3202.62) incorrectly attempts to translate index page

### ISSUE THREAD

**Issue by barryels** [adambard/learnxinyminutes-site#44]
![screen shot 2017-10-24 at 19 13 30](https://user-images.githubusercontent.com/872849/31994485-17d5c81c-b981-11e7-81af-800a5b3c1c4e.png)

**Comment by divayprakash** [comment]
@adambard Fix has been merged, this issue can be closed.

**Comment by divayprakash** [comment]
@adambard This is still a problem on Google Chrome (v71.0.3578.98) on Windows.

**Comment by divayprakash** [comment]
The way I see it we can solve this using
```html
<meta name="google" content="notranslate">
```
However, this will then apply to all the pages on the site and prevent user from translating them to a language other than the page language if desired.

**Comment by adambard** [comment]
I'm not really worried about this -- if Chrome thinks the page needs translating, that's Chrome's problem.
