### ISSUE TITLE
Certificate expired on December 25

### ISSUE THREAD

**Issue by Menelion** [adambard/learnxinyminutes-site#56]
**Migrated from adambard/learnxinyminutes-docs#3433**

@jimpallomeni in adambard/learnxinyminutes-docs#3433 reports:

> Please renew your Let's Encrypt certificate for the site.

**Comment by divayprakash** [comment]
![image](https://user-images.githubusercontent.com/11337492/50569017-643ade80-0d82-11e9-8537-8bff1a756ec8.png)

Seems to be fixed now. This issue can be closed!

**Comment by Menelion** [comment]
Thanks @divayprakash!

**Comment by jimpallomeni** [comment]
Thanks everyone

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Menelion** [comment]
Certificate expiration reported again in adambard/learnxinyminutes-docs#3485.

**Comment by Menelion** [comment]
Copying @z-adams here.

**Comment by adambard** [comment]
sorted, looks like I have more crontab debugging to do.
