### ISSUE TITLE
i18n issue

### ISSUE THREAD

**Issue by imba-tjd** [adambard/learnxinyminutes-site#72]
I found the values of `Select theme` are not properly synced with the source data.

This is not correct:

![image](https://user-images.githubusercontent.com/24759802/69030977-fb00a000-0a13-11ea-9159-71b0dbc1e5a9.png)

but the entry in https://github.com/adambard/learnxinyminutes-site/blob/master/data/i18n.yaml is correct

![image](https://user-images.githubusercontent.com/24759802/69031011-12d82400-0a14-11ea-9273-f5aaa2526839.png)

Besides, I cannot see how many people modified the files. For example the [yaml tutorial](https://learnxinyminutes.com/docs/zh-cn/yaml-cn/). It says "updated by 0 contributors":

![image](https://user-images.githubusercontent.com/24759802/69031117-4ca92a80-0a14-11ea-815f-3a4c3183256d.png)

This two issues exist both in zh-cn and zh-tw. I don't know others.

**Comment by verhovsky** [comment]
Seems to be fixed now.
