### ISSUE TITLE
The site's markdown rendering is significantly different from github's.

### ISSUE THREAD

**Issue by anakimluke** [adambard/learnxinyminutes-site#77]
## The problem

I was about to make a contribution to a page when I noticed that what I thought was a typo was actually a disparity in the way [leanxinyminutes](https://learnxinyminutes.com/docs/set-theory/) and  [github](https://github.com/adambard/learnxinyminutes-docs/blob/master/set-theory.html.markdown) handle markdown.

#### learnxinyminutes:
![image](https://user-images.githubusercontent.com/22756345/84715761-d50a9200-af47-11ea-81b4-9b8333939b56.png)

#### github:
![image](https://user-images.githubusercontent.com/22756345/84715785-eb185280-af47-11ea-8dab-40220c51258e.png)

#### learnxinyminutes:
![image](https://user-images.githubusercontent.com/22756345/84716132-b658cb00-af48-11ea-9a92-e3dd44ed660b.png)

#### github:
![image](https://user-images.githubusercontent.com/22756345/84716156-bf499c80-af48-11ea-84eb-390697845ebe.png)

## Possible fix

I'm not a ruby programmer, but from what I dug up it might be a good idea to switch from Middleman's default RedCarpet, to something that implements github flavored markdown.

This way, both contributors and auditors could rely on/count with github's md preview, instead of cloning the site/building the site every time.

Other relevant links:
- https://about.gitlab.com/blog/2019/06/13/how-we-migrated-our-markdown-processing-to-commonmark/
- https://gitlab.com/digitalmoksha/diff_redcarpet_cmark
- https://github.com/github/cmark-gfm
- https://babelmark.github.io/

**Comment by verhovsky** [comment]
GitHub uses https://github.com/gjtorikian/commonmarker which Middleman doesn't support https://github.com/middleman/middleman/issues/2420
